### ISSUE TITLE
Typ pola "date"

### ISSUE THREAD

**Issue by adwydman** [Sealious/sealious-base-chips#10]

**Comment by arkadiusz-wieczorek** [comment]
Powinniśmy posługiwać się standardem ISO 8601, jeśli chodzi o datę obowiązuje następująca notacja
`YYYY-MM-DD` zawsze należy podawać w postaci 4 cyfr dla roku, bo ten problem generuje najwięcej pomyłek. Jeśli chodzi o standard amerykański posługują się najczęściej `MM-DD-YYYY` ale i też naszym ISO, który nazywa się inaczej.

Wg ISO 8601

``` javascript
YYYY-MM-DD  or  YYYYMMDD
YYYY-MM (but not YYYYMM)
```

http://en.wikipedia.org/wiki/ISO_8601
http://tools.ietf.org/html/rfc3339#section-5

Jeśli o chodzi domyślną funkcję `Date.parse()` należy podać separator, to czy będzie to format określony przez ISO 8601 czy też nie, decyduje kolejność podanych parametrów. Więc możemy rozpatrywać oba formaty w następujący sposób. Sprawdzamy jaki został podany string musi zawierać separatory oraz to czy cztery cyfry są na początku czy też.

``` javascript
Date.parse("06-14-2015") //notacja amerykańska
1434232800000
Date.parse("2015-06-14") //notacja ISO 8601
1434240000000
Date.parse("14-06-2015") //typowa data "po polsku"
NaN
```

Output to liczba milisekund, które upłynęły od 1 stycznia 1970, 00:00:00 UTC

Różne timestampy, które definiują tę samą datę, czyli prawdopodobnie w timestampie jest zaszyta informacja czy użyto do jego wygenerowania standardu A czy B.

``` javascript
var d = new Date(1434240000000);
undefined
d
Sun Jun 14 2015 02:00:00 GMT+0200 (CEST)

var s = new Date(1434232800000)
undefined
s
Sun Jun 14 2015 00:00:00 GMT+0200 (CEST)
```

**Comment by kuba-orlik** [comment]
Niet - timestamp to ilość millisecond od epoki i nie ma w nim informacji o
formatowaniu - podane daty różnią się o 2 godziny z jakiegoś powodu

**Comment by kuba-orlik** [comment]
Proponuję:
*dla dat z granuralnością co do dnia przyjmować tylko format ISO
*dla dat z granuralnością co do minuty/godziny przyjmować tylko timestamp.
To wyeliminuje bawię nie się w strefy czasowe i co nie tylko.
Kto za?

**Comment by arkadiusz-wieczorek** [comment]
Faktycznie nie zauważyłem tej godziny patrzyłem na GMT. Poszedłbym właśnie w format ISO 8601 jest to międzynarodowym standard poparty przez dokument RFC. Co do USA czy UK wystarczy że podamy do dokumentacji obowiązujący format. Jeśli dany deweloper oczekuje przypadku użycia daty obowiązującej w USA/UK to powinien napisać własne pole typu field-date.

Co do minuty/godziny jak najbardziej timestamp jest całkowicie jednoznaczny.

**Comment by arkadiusz-wieczorek** [comment]
Gotowy field_type.date
https://github.com/Sealious/sealious-base-chips/commit/e6684214d2eb676fd2444eb556d5e35cbedb1b59

Do przetestowania w example-app (niestety poszło w branch testing dla typu pola float)
https://github.com/Sealious/sealious-example-app/commit/ed14510750bcd8b62716b6d8cfdd382f667cc0e6

Pull request
https://github.com/Sealious/sealious-base-chips/pull/21
