### ISSUE TITLE
Automatyczne tworzenie ścieżek restowych

### ISSUE THREAD

**Issue by kuba-orlik** [Sealious/sealious-base-chips#16]
Aktualnie aby dodać zasób do RESTowego api należy wywołać przykładowo:

``` js
rest.add_path("/api/v1/form_entry", "form_entry");
```

Jak chcemy dodać kilka zasobów, to kod szybko puchnie:

``` js
rest.add_path("/api/v1/form_entry", "form_entry");
rest.add_path("/api/v1/stoiska", "stoisko");
rest.add_path("/api/v1/firmy", "firma");
rest.add_path("/api/v1/no_html", "no_html");
```

Należy tak zmienić kod, aby wystarczyło zrobić:

``` js
rest.set_url_base("/api/v1/")
```

Wtedy kanał restowy ma reagować na wszystkie typy zasobów, np na zasoby typu "form_entry" pod url-em "api/v1/form_entry", itp.

Kwestia do dyskusji - czy w `set_url_base` należy podawać url z forward slashem na końcu, czy bez?

**Comment by adwydman** [comment]
Jak wtedy deklarowało by się zasoby? Może coś w stylu:

``` JavaScript
var array = ["form_entry", "stoisko", "firma", "no_html"];
rest.set_paths("/api/v1/", array);
```

Co wy na to?

**Comment by kuba-orlik** [comment]
Chodzi o to, że rest api ma utworzyć api dla wszystkich zadeklarowanych
zasobów

**Comment by adwydman** [comment]
Nie wiem czym by się to miało różnić od tego co napisałem. :)

**Comment by kuba-orlik** [comment]
W Twoim rozwiązaniu musimy ręcznie stworzyć array z nazwami typów zasobów -
a rest powinien po prostu automatycznie tworzyć api dla każdego zasobu

**Comment by adwydman** [comment]
Jak w takim razie deklarowałbyś typy zasobów?

**Comment by kuba-orlik** [comment]
Tak, jak dotychczas:

``` js
var form_entry = new Sealious.ChipTypes.ResourceType("form_entry"); 

form_entry.add_fields([
    {name: "first-name", type: "text", required: true, params: {max_length: 5}},
    {name: "last-name", type: "text", required: true},
    {name: "PESEL", type: "text", required: true},
    {name: "favorite-color", type: "color"},
    {name: "stoisko", type: "reference", required: true, params:{allowed_types:["stoisko"]}}
])
```

Nie chodzi mi o zastąpienie deklaracji typów zasobow, tylko o eliminację potrzeby przypinania ręcznie każdego typu zasobu do przewidywalnej ścieżki restowej :)

**Comment by adwydman** [comment]
A, ok, teraz rozumiem :)

2015-04-29 12:47 GMT+02:00 Kuba Orlik notifications@github.com:

**Comment by arkadiusz-wieczorek** [comment]
"Kwestia do dyskusji - czy w set_url_base należy podawać url z forward slashem na końcu, czy bez?"

Na pewno bez slasha na końcu.

**Comment by kuba-orlik** [comment]
Skąd ta pewność? :D

**Comment by arkadiusz-wieczorek** [comment]
Wszędzie gdzie natknąłem się na restowe ścieżki nie istniał '/' na końcu, wyjątkiem jest amygdala.
