### ISSUE TITLE
Typ pola 'float'

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [Sealious/sealious-base-chips#17]
Przyda się typ pola zmiennoprzecinkowy, co ciekawe podczas dodawania nowego zasobu w Amygdala  dodaje normalnie dane liczbowe w postaci stringa, lecz gdy wykonuje put na danym zasobie to nowe dane liczbowe są już w postaci liczby.

**Comment by arkadiusz-wieczorek** [comment]
Gotowy typ pola float w sealious-base-chips
https://github.com/Sealious/sealious-base-chips/commit/d58f23d86ba02b7feb1744a89362a1c1fe631436

Do przetestowania w example-app
https://github.com/Sealious/sealious-example-app/commit/67f9141bfcf0061da594542a727d585ab7021864

**Comment by kuba-orlik** [comment]
Najs!
Hmm czemu aż dwa testy na bycie floatem? Samo parseFloat nie działało
dobrze?

**Comment by arkadiusz-wieczorek** [comment]
Bo jeśli podamy liczbę całkowitą to parseFloat zwróci po prostu tę liczbę. Zatem jeśli to faktycznie ma być pole typu float, trzeba sprawdzać czy aby na pewno jest to float stąd drugi test.

**Comment by kuba-orlik** [comment]
Czyli nie przyjmujemy tutaj liczb całkowitych?

**Comment by arkadiusz-wieczorek** [comment]
Tak

**Comment by kuba-orlik** [comment]
Jestem przekonany, że powinniśmy! Inaczej to pole dopuści 2.0000001, ale ma
nie dopuścić 2?
​

**Comment by arkadiusz-wieczorek** [comment]
Ok zmodyfikuje kod

**Comment by arkadiusz-wieczorek** [comment]
Poprawiona wersja do przetestowania https://github.com/Sealious/sealious-base-chips/commit/5622e1b2daea55c6478d0c21f3e2c179e8bd74da
Pull request https://github.com/Sealious/sealious-base-chips/pull/18
