### ISSUE TITLE
REST - Problem response z metodą PUT

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [Sealious/sealious-base-chips#19]
Metoda PUT zwraca `1` a powinna zwracać reprezentację zasobu.

**Comment by kuba-orlik** [comment]
Po zajrzeniu w kod okazuje się, że jest to problem z ResourceManagerem - powinien zwracać Resource, a zwraca ilość zaktualizowanych dokumentów (tj 1). 
Issue w repo Core'a: https://github.com/Sealious/Sealious/issues/152
Pull Request: https://github.com/Sealious/Sealious/pull/153

**Comment by arkadiusz-wieczorek** [comment]
Przetestowane, rozwiązało problem z modelem od Amygdala! :+1:
