### ISSUE TITLE
Typ pola 'file'

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [Sealious/sealious-base-chips#29]
Aktualnie file manager działa niezależnie od innych zasobów. W praktyce zależy nam na większym powiązaniu. Upload pliku mógłby być obsługiwany z pola typu 'file'.

Moja propozycja:
wysyłamy zapytanie typu POST wraz z plikiem na dany zasób, a serwer zapewnia że dany plik otrzyma jako nazwę - id tego konkretnego, tworzonego dokumentu zasobu i będzie dostępny pod zdefiniowanym katalogiem na serwerze.

Przykładowy dokument zasobu mógłby wyglądać tak:

``` json
{
"some_value" : "ala ma kota",
"some_value2" : "ala ma dwa koty",
"file": "true",
"file_extension" : "jpg",
"owner_id": "n0c8w60i2r",
"id": "j16u69ulwt",
"access_mode": "private",
"type": "zasob"
}
```

Wtedy docelowa aplikacja wiedziałaby, że należy zapytać o plik pod znanym adresem, który ustaliliśmy do uploadu. Np. coś takiego `/files/n0c8w60i2r/j16u69ulwt.jpg`

Oczywiście te rozwiązanie zapewnia powiązanie typu jeden plik + jeden dokument.

**Comment by simplypixi** [comment]
Nie rozumiem. xD
Teraz informacje na temat plików są również przechowywane w bazie, gdzie
nazwa pliku (uid) to sealious_id dokumentu w kolekcji "files". ;)

**Comment by kuba-orlik** [comment]
Jeżeli dobrze rozumiem to chodzi o to, aby można było tworzyć pole typu
"plik" - a przy zapytaniu GET na zasób z takim polem dostać bezwzględny url
do pliku.
Juz pracuje nad tym na osobnym branchu (zawinę po prostu odwołania do
FileManagera w FieldType'a) :)

**Comment by simplypixi** [comment]
Spoczi ;)

**Comment by arkadiusz-wieczorek** [comment]
O właśnie - sealious_id to id z kolekcji files, a chodzi o to żeby móc wykorzystywać obsługę plików w innych kolekcjach wprost z pola typu file. :)

**Comment by kuba-orlik** [comment]
Zrobione! Zrobiłem dodatkowe commity na branchach Mariusza, polecam obczaić! :)
